bibliotheque/urls.py
from django.contrib import admin
from django.urls import path
from appBibliotheque.views import (
    home, rechercher_livre, detail_livre, ajouter_livre, ajouter_exemplaire,
    page_UnLivre, filterLivre, edit_livre, liste_demandes_emprunt, rendre_exemplaire,
    mise_pret_horspret, emprunter_exemplaire, liste_livres, page_ajout, supprimer_exemplaire,
    detailLivre, dashboard, update_livre, demande_emprunt, refuser_demande_emprunt,
    accepter_demande_emprunt, list_exemplaire_empruntes,ajouterEmprunt
)
from accounts.views import (
    register, signup, pagelogin, login_user, logout_user, users_lists, delete_user,
    forget_password_view
)
from  accounts.decorators import bibliothecaire_required
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('register/', register, name='register'),
    path('genre/<str:genre>', filterLivre, name='filterLivre'),
    path('page_UnLivre/', page_UnLivre, name='page_UnLivre'),
    path('signup/', signup, name='signup'),
    path('forgot_password/', forget_password_view, name='forgot_password'),
    path('logout_user/', logout_user, name='logout_user'),
    
    path('users_lists/', bibliothecaire_required(users_lists), name='users_lists'),
    path('delete_user/<slug:username>',bibliothecaire_required(delete_user)  , name='delete_user'),
    path('page_ajout/', bibliothecaire_required(page_ajout) , name='page_ajout'),
    path('pagelogin/', pagelogin, name='pagelogin'),
    path('rechercher_livre/', rechercher_livre, name='rechercher_livre'),
    path('ajouter_livre/', bibliothecaire_required(ajouter_livre), name='ajouter_livre'),
    path('edit_livre/<int:id>', bibliothecaire_required(edit_livre), name='edit_livre'),
    path('update_livre/<int:id>', bibliothecaire_required(update_livre), name='update_livre'),
    path('liste_livres/', bibliothecaire_required(liste_livres), name='liste_livres'),
    path('supprimer_exemplaire/<int:id>', bibliothecaire_required(supprimer_exemplaire), name='supprimer_exemplaire'),
    path('detail_livre/<slug:slug>', detail_livre, name='detail_livre'),
    path('ajouter_exemplaire/<int:id>', bibliothecaire_required(ajouter_exemplaire), name='ajouter_exemplaire'),
    path('detailLivre/<int:id>',  bibliothecaire_required(detailLivre), name='detailLivre'),
    path('livre/<slug:slug>/emprunter_exemplaire', emprunter_exemplaire, name='emprunter_exemplaire'),
    path('login/', login_user, name='login'),
    path('dashboard/', bibliothecaire_required(dashboard), name="dashboard"),
    path('liste_demandes_emprunt/', bibliothecaire_required(liste_demandes_emprunt), name="liste_demandes_emprunt"),
    path('list_empruntes/', bibliothecaire_required(list_exemplaire_empruntes), name="list_empruntes"),
    path('refuser_demande_emprunt/<int:id>', bibliothecaire_required(refuser_demande_emprunt), name="refuser_demande_emprunt"),
    path('accepter_demande_emprunt/<int:id>', bibliothecaire_required(accepter_demande_emprunt), name="accepter_demande_emprunt"),
    path('rendre_exemplaire/<int:id>', bibliothecaire_required(rendre_exemplaire), name="rendre_exemplaire"),
    path('mise_pret_horspret/<int:id>', bibliothecaire_required(mise_pret_horspret), name="mise_pret_horspret"),
    path('demande_emprunt/', demande_emprunt, name="demande_emprunt"),
    
    path('ajouterEmprunt/',bibliothecaire_required(ajouterEmprunt), name="ajouterEmprunt")
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appBibliotheque/models.py
from django.db import models
from accounts.models import Utilisateur
from django.urls import reverse

class Livre(models.Model):
    id = models.AutoField(primary_key=True)
    auteur = models.CharField(max_length=128)
    titre = models.CharField(max_length=128)
    isbn = models.CharField(max_length=50, unique = True)
    slug = models.SlugField(max_length=200)
    description = models.TextField()
    date_publication = models.DateField(auto_now_add=True)
    image_couverture = models.ImageField(upload_to ='images',null = True,blank = True)
    categories = models.CharField(max_length=128,null = True)
    def get_NbrExemple(self):
        return self.exemplaires_livre.count()
        # return self.exemplaires_livre.count()+1
    def __str__(self) -> str:
        return self.titre 
    def get_absolute_url(self):
        return reverse("livre",kwargs={'slug': self.slug})
    def save(self, *args, **kwargs):
        # Si le slug n'est pas déjà défini, le créer à partir de l'ISBN
        if not self.slug:
            self.slug = self.isbn
        super().save(*args, **kwargs)
    def is_disponible(livre_id):
        return Exemplaire.objects.filter(livre_id=livre_id,disponible=True).exists()
class Exemplaire(models.Model):
    id = models.AutoField(primary_key=True)
    livre = models.ForeignKey(Livre,on_delete=models.CASCADE,related_name='exemplaires_livre')
    disponible = models.BooleanField(default=True) 
    perdu = models.BooleanField(default=False)
class Emprunter(models.Model):
    exemplaire = models.OneToOneField(Exemplaire,on_delete=models.CASCADE)
    utilisateur = models.ForeignKey(Utilisateur,on_delete=models.CASCADE)
    date_emprunt = models.DateField(auto_now_add=True)
    date_retour = models.DateField(blank=True, null = True)
    accepter = models.BooleanField(default=False)
    
class DemandeEmprunt(models.Model):
    id_demande = models.AutoField(primary_key=True)
    exemplaire = models.ForeignKey(Exemplaire, on_delete=models.CASCADE)
    utilisateur = models.ForeignKey(Utilisateur, on_delete=models.CASCADE)
    date_demande = models.DateTimeField(auto_now_add=True)
    date_retour = models.DateField(blank=True,null=True)
    acceptee = models.BooleanField(default=False)

appBibliotheque/views.py
from django.shortcuts import render,redirect,get_object_or_404
from appBibliotheque.models import Livre,Emprunter,Exemplaire,DemandeEmprunt
from django.contrib import messages
from django.core.mail import BadHeaderError,send_mail
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator 
from accounts.models import Utilisateur
from datetime import datetime
def get_paginated_books(request, livres):
    paginator = Paginator(livres, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj

def home(request):
    livres = Livre.objects.order_by('id')
    page_obj = get_paginated_books(request, livres)
    return render(request, 'appBibliotheque/user/home.html', {'page_obj': page_obj})

def rechercher_livre(request):
    query = request.GET.get('titre')
    livres = Livre.objects.filter(titre__icontains=query) if query else []
    page_obj = get_paginated_books(request, livres)
    message = "No search query provided." if not query else ""
    return render(request, 'appBibliotheque/user/home.html', {'page_obj': page_obj, 'query': query, 'message': message})  


def detail_livre(request,slug):
    livre = get_object_or_404(Livre,slug=slug)
    return render(request,'appBibliotheque/user/unLivre.html',{"livre_detail":livre})


def emprunter_exemplaire(request, slug):
    
    livre = get_object_or_404(Livre, slug=slug)
    message = ""
    # Vérifier si l'utilisateur a déjà emprunté ce livre
    utilisateur = request.user 
    if Emprunter.objects.filter(utilisateur=utilisateur, exemplaire__livre=livre).exists():
        message = f"Vous avez déjà emprunté le livre '{livre.titre}'."
    else:
        # Vérifier si des exemplaires sont disponibles
        exemplaires_disponibles = Exemplaire.objects.filter(livre=livre, disponible=True)
        if exemplaires_disponibles.exists():
            exemplaire = exemplaires_disponibles.first()
            # Créer un nouvel emprunt
            emprunt = Emprunter.objects.create(exemplaire=exemplaire, utilisateur=utilisateur)
            emprunt.save()
            # Mettre à jour la disponibilité de l'exemplaire
            exemplaire.disponible = False
            exemplaire.save()
            message = f"L'exemplaire du livre '{livre.titre}' a été emprunté avec succès."
        else:
            message = f"Aucun exemplaire disponible pour le livre '{livre.titre}'."
    
    return render(request, 'appBibliotheque/user/home.html', {'livre': livre, 'message': message})


@login_required
def liste_livres(request):
   
    query = request.GET.get('nom')
    
   
    message=""
    if query:
        livres = Livre.objects.filter(titre__icontains=query)
        
        
        if not livres :
            message = "Aucun livre trouvé ."
    else:
        livres = Livre.objects.all()
    page_obj = get_paginated_books(request, livres)
    return render(request,'appBibliotheque/dashboard/livre.html',{'livres' : livres ,'page_obj':page_obj,'message': message,query:"query"})

def page_ajout(request):
    return render(request, 'appBibliotheque/dashboard/ajouter.html')

def edit_livre(request,id):
    livre = get_object_or_404(Livre,id=id)
    return render(request,'appBibliotheque/dashboard/edit.html',{'livre' : livre })

def update_livre(request, id):
    livre = get_object_or_404(Livre, id=id)
    if request.method == 'POST':
        titre = request.POST.get('titre')
        auteur = request.POST.get('auteur')
        isbn = request.POST.get('isbn')
        categories = request.POST.get('categories')
        description = request.POST.get('description')
        image_couverture = request.FILES.get('image_couverture')

        livre.titre = titre
        livre.auteur = auteur
        livre.isbn = isbn
        livre.categories = categories
        livre.description = description
        if image_couverture:
            livre.image_couverture = image_couverture
        livre.save()
        messages.success(request, "Le livre a été mis à jour avec succès.")
        
        return redirect('liste_livres')

    return render(request, 'appBibliotheque/dashboard/edit.html', {'livre': livre})


def ajouter_livre(request):
    
    if request.method == 'POST':
        titre = request.POST.get('titre')
        auteur = request.POST.get('auteur')
        isbn = request.POST.get('isbn')
        categories = request.POST.get('categories')
        description = request.POST.get('description')
        image_couverture = request.FILES.get('image_couverture')
        livre = Livre(titre=titre, auteur=auteur, isbn=isbn,categories=categories, description=description, image_couverture=image_couverture)
        if titre and auteur and isbn and description and image_couverture:
            livre.save()
            Exemplaire.objects.create(livre=livre, disponible=True)
            messages.success(request, "Le livre a été ajouté avec succès.")
            return redirect("liste_livres")  # Assurez-vous que 'acceuileBli' est correct
        else:
            messages.error(request, "Le formulaire nest pas valide. Veuillez corriger les erreurs.")
            return redirect("ajouter_livre")
    else:
       return render(request, 'appBibliotheque/dashboard/ajouter.html')
   
   
def supprimer_exemplaire(request,id):
    
    livre = get_object_or_404(Livre,id=id)
    exemplaires = Exemplaire.objects.filter(livre=livre,disponible = True)
    if exemplaires.exists():
        
        exemplaire = exemplaires.first()
        exemplaire.delete()
        messages.success(request,"le exemplaire est supprime avec succès")
        return redirect('liste_livres')
    else:
        return redirect('liste_livres')
    
def ajouter_exemplaire(request, id):
    livre = get_object_or_404(Livre,id=id)
    exemplaire = Exemplaire.objects.create(livre = livre, disponible=True)
    exemplaire.save()
    return redirect('liste_livres')

def detailLivre(request,id):
    livre = get_object_or_404(Livre,id=id)
  
    exemplaires = Exemplaire.objects.filter(livre=livre)#disponible = True
    nbExemplaire=Exemplaire.objects.count();

    return render(request,'appBibliotheque/dashboard/detailLivre.html',{'livre':livre,'exemplaires':exemplaires})

def page_UnLivre(request):
    return render(request,'appBibliotheque/user/unLivre.html')

def filterLivre(request,genre):
    if(genre=="all"):
         livres = Livre.objects.order_by('id')
    else:
       livres = Livre.objects.order_by('id').filter(categories__icontains=genre)
    page_obj = get_paginated_books(request, livres)
   
    return render(request,'appBibliotheque/user/home.html', {'genre': genre, 'page_obj': page_obj}) 

def dashboard(request):
    nbUsers = Utilisateur.objects.all().filter(est_bibliothecaire=False).count()
    nbLivres=Livre.objects.all().count()
    nbEmpruntes=Emprunter.objects.all().count()
    nbExemplairePerdu=Exemplaire.objects.all().filter(perdu=True).count()
    context={
        "nbUsers":nbUsers,
         "nbLivres":nbLivres,
         "nbEmpruntes":nbEmpruntes,
         "nbExemplairePerdu":nbExemplairePerdu
    }
    return render(request,'appBibliotheque/dashboard/dashboard.html',context)



def demande_emprunt(request):
    if request.method == 'POST':
        try:
            utilisateur = request.user
            id = request.POST.get("id")
            exemplaire = Exemplaire.objects.filter(livre_id=id, disponible=True).first()
            # print(Exemplaire.objects.filter(livre_id=id, disponible=True).query)

            if exemplaire and exemplaire.disponible:
                demande_existante = DemandeEmprunt.objects.filter(exemplaire=exemplaire, 
                                                                  utilisateur=utilisateur,
                                                                  acceptee=False).exists()
                if demande_existante:
                    messages.warning(request, "Vous avez déjà une demande en cours pour cet exemplaire.")
                else:
                    date_retour_str = request.POST.get('date_retour')
                    try:
                        date_retour = datetime.strptime(date_retour_str, '%Y-%m-%d')
                        demande = DemandeEmprunt.objects.create(exemplaire=exemplaire, 
                                                                utilisateur=utilisateur,
                                                                date_retour=date_retour)
                        demande.save()
                        messages.success(request, "Le livre a été demandé avec succès.")
                    except ValueError:
                        messages.error(request, "Format de date invalide.")
            else:
                messages.warning(request, "Cet exemplaire n'est pas disponible.")
        except Exception as e:
            print(e)
            messages.error(request, f"Une erreur s'est produite : {e}")
    return redirect("home")


# def is_admin(user):
#     return user.est_bibliothecaire

	

    









@login_required
def liste_demandes_emprunt(request):
    # Récupérer toutes les demandes d'emprunt
    demandes = DemandeEmprunt.objects.all().order_by("date_demande")
    
    return render(request, 'appBibliotheque/dashboard/demande_Empruntes.html',
                  {'demandes': demandes})

def accepter_demande_emprunt(request, id):
    demande = get_object_or_404(DemandeEmprunt, pk=id)
    print(demande.exemplaire)
    
    exemplaire = Exemplaire.objects.get(id=demande.exemplaire.id, disponible=True)
        
    utilisateur = demande.utilisateur
    livre = exemplaire.livre

    if Emprunter.objects.filter(utilisateur=utilisateur, exemplaire__livre=livre).exists():
        messages.warning(request, f"Vous avez déjà emprunté le livre '{livre.titre}'.")
    else:
        # Créer un nouvel emprunt

appBibliotheque/templates/appBibliotheque/dashboard/ajouter.html
{% extends './base.html' %}

{% load static  %}

{% block header %}
Ajouter Livre
{% endblock %}

{% block content %}

<form action="{% url 'ajouter_livre' %}" method="post" enctype="multipart/form-data" >
  {% csrf_token %}
  <div class="inputs">
      <input name="titre" class="input" placeholder="Nom Livre"  >
      <input name="isbn" class="input" placeholder="ISBN">
      <input name="auteur" class="input" placeholder="auteur" >
      <input name="categories" class="input" placeholder="Categories" >
  
    </div>
  
    <div class="field">

     <textarea name="description" class="input" id="" cols="100" rows="10"   placeholder="Description">{{ livre.description }}</textarea>
      
    </div>
    <div class="img_ajouter">
        <img id="imgprv"/>
   
      </div>
    <label class="custum-file-upload" for="file">
      <div class="icon">
      <svg xmlns="http://www.w3.org/2000/svg" fill="" viewBox="0 0 24 24"><g stroke-width="0" id="SVGRepo_bgCarrier"></g><g stroke-linejoin="round" stroke-linecap="round" id="SVGRepo_tracerCarrier"></g><g id="SVGRepo_iconCarrier"> <path fill="" d="M10 1C9.73478 1 9.48043 1.10536 9.29289 1.29289L3.29289 7.29289C3.10536 7.48043 3 7.73478 3 8V20C3 21.6569 4.34315 23 6 23H7C7.55228 23 8 22.5523 8 22C8 21.4477 7.55228 21 7 21H6C5.44772 21 5 20.5523 5 20V9H10C10.5523 9 11 8.55228 11 8V3H18C18.5523 3 19 3.44772 19 4V9C19 9.55228 19.4477 10 20 10C20.5523 10 21 9.55228 21 9V4C21 2.34315 19.6569 1 18 1H10ZM9 7H6.41421L9 4.41421V7ZM14 15.5C14 14.1193 15.1193 13 16.5 13C17.8807 13 19 14.1193 19 15.5V16V17H20C21.1046 17 22 17.8954 22 19C22 20.1046 21.1046 21 20 21H13C11.8954 21 11 20.1046 11 19C11 17.8954 11.8954 17 13 17H14V16V15.5ZM16.5 11C14.142 11 12.2076 12.8136 12.0156 15.122C10.2825 15.5606 9 17.1305 9 19C9 21.2091 10.7909 23 13 23H20C22.2091 23 24 21.2091 24 19C24 17.1305 22.7175 15.5606 20.9844 15.122C20.7924 12.8136 18.858 11 16.5 11Z" clip-rule="evenodd" fill-rule="evenodd"></path> </g></svg>
      </div>
      <div class="text">
         <span id="filename">Click to upload image</span>
         </div>
         <input type="file" name="image_couverture" id="file" onchange="previewImage(event)">
    

      </label>
     
      
      <div class="btn">
        <button type="submit">Ajouter</button>

      </div>
 </form>
 <script>
    function previewImage(event) {
      const file = event.target.files[0];
      if (file) {
        const reader = new FileReader();
        reader.onload = function (e) {
          document.getElementById("imgprv").src = e.target.result;
        };
        reader.readAsDataURL(file);
        document.getElementById("filename").textContent = file.name;
      }
    }
 

  </script>

{% endblock %}

appBibliotheque/templates/appBibliotheque/dashboard/ajouterEmprunt.html
{% extends './base.html' %}

{% load static  %}

{% block header %}
Ajouter Emprunt
{% endblock %}

{% block content %}

<form action="{% url 'ajouter_livre' %}" method="post" enctype="multipart/form-data" >
  {% csrf_token %}
  <div class="inputs2">
      <input name="nom" class="input" placeholder="Nom"  >
      <input name="prenom" class="input" placeholder="prenom">
      <input name="email" class="input" placeholder="email" >
   
  
    </div>
  
   
     
      
     
      <div style="overflow-x:auto;">
        <table>
          <tr>
            <th>Id</th>
            <th>ISBN</th>
            <th>Nom Livre</th>
            <th>Auteur</th>
            <th>nb exemplaire</th>
            <th>disppnible</th>
            <th>action</th>
          </tr>
          {% for livre in livres %}
          <tr>
            <td>{{livre.id}}</td>
            <td>{{livre.isbn}}</td>
            <td>{{livre.titre}}</td>
            <td>{{livre.auteur}}</td>
            <td>{{ livre.get_NbrExemple }}</td>
            {% if livre.is_disponible %}
            <td class="etat"> <span class="true">true</span></td>
            {% else %}
            <td class="etat"> <span class="false">false</span>    </td>
            {% endif %}
            <td class="action">
                {% if livre.is_disponible %}
                <input type="radio" name="${id}" id="">
                {% else %}
               
                {% endif %}
          
            </td>
          </tr>
          {% endfor %}
        </table>
        <div class="pagination" style="margin:20px auto; width:max-content">
         <span class="step-links">
             {% if page_obj.has_previous %}
             <a class="paginateflesh" href="?page={{ page_obj.previous_page_number }}"> <i class="fa-solid fa-chevron-left"></i>  précédente</a>
             <a class="current">
                 Page {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
             </a>
             <a class="paginateflesh" href="?page=1"> première <i class="fa-solid fa-chevron-right"></i></a>
     
             {% endif %}
     
           
             {% if page_obj.has_next %}
             <!-- <a  class="paginateflesh" href="?page={{ page_obj.paginator.num_pages }}"> <i class="fa-solid fa-chevron-left"></i> dernière </a> -->
             <a class="current">
                 Page {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
             </a>
             <a class="paginateflesh" href="?page={{ page_obj.next_page_number }}"> suivante <i class="fa-solid fa-chevron-right"></i></a>
     
             {% endif %}
         </span>
     </div>
      </div> 
      <div class="btn">
        <button type="submit">Ajouter</button>

      </div>
     
 </form>


{% endblock %}

appBibliotheque/templates/appBibliotheque/dashboard/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bibliotheque</title>
    <link rel="stylesheet" href ="{% static 'style/dashboard/ajouterEmprunt.css' %}" />
    <link rel="stylesheet" href="{% static 'style/global.css' %}" />
    <link rel="stylesheet" href="{% static 'style/dashboard/dashboard.css' %}" />
    <link rel="stylesheet" href="{% static 'style/dashboard/livre.css' %}" />
    <link rel="stylesheet" href ="{% static 'style/dashboard/ajouter.css' %}" />
    <link rel="stylesheet" href ="{% static 'style/dashboard/detailLivre.css' %}" />
    
    <link
      rel="stylesheet"
      href="{% static 'style/fontawesome-free-6.5.2-web/css/all.min.css' %}" />
</head>
<body>
<style>


</style>
    <div class="countainer">
        {% include './layout/sidebar.html' %} 
        <div class="main">
          <div>
            <div class="header">
              <div class="location open" >
                <i class="fa-solid fa-bars"></i>
                <h2>
                  {% block header %}{% endblock %}
                </h2>
              </div>
              <div class="right">
                <form class="search_container" method="get" action="{{request.path}}" >
                  <input type="text" name="nom" class="search" value="{{ query|default:'' }}" placeholder="Search.." style="width: 100%;">
                  
                  <button type="submit">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="searchIcon">
                          <path fill="#bdbdbd" d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"/>
                      </svg>
                  </button>
             </form>
              
              </div>
            </div>
            
  
            <div class="content">
            
                {% block content %}{% endblock %}
         
            
            </div>
          </div>
        </div>
      </div>
      <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->
 
  
    <script src="{% static 'js/sidebar.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
   {% if messages %}
   {% for message in messages %}
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                    Swal.fire({
                        title: '{{ message.tags }}',
                        text: '{{ message }}',
                        icon: '{{ message.tags }}'
                        
                    });
                  });
                </script>
      {% endfor %}
      
    {% endif %}
</body>
</html>

appBibliotheque/templates/appBibliotheque/dashboard/demande_Empruntes.html
{% extends './base.html' %}
{% load static %}
{% block header %}
Liste Demande
{% endblock %}
{% block content %}

<div class="btndash">
 <!-- <a href="{% url 'page_ajout' %}"> les Demande d'emprunte   <i class="fa-solid fa-plus"></i></a> -->

</div>


 <div class="content" style=" margin:0px 0;">  
   {% if demandes %}
 <div style="overflow-x:auto;">
   <table>
     <tr>
       <th>Livre</th>
       <th>User</th>
       <th>date de demande </th>
       <th>Action</th>
       
     </tr>
  
      
     
     {% for demande in demandes %}
     <tr>
       
       <td>{{demande.exemplaire.livre.titre }}</td>
       <td>{{ demande.utilisateur.username }}</td>
     
       <td>{{ demande.date_demande }}</td>
     
         <td class="etat">  <a href="{% url 'accepter_demande_emprunt' demande.id_demande  %}"><span class="true">accepter</span></a>
     
         <td class="etat">  <a href="{% url 'refuser_demande_emprunt' demande.id_demande  %}"><span class="false">Refuser</span></a>
      
     
       <td class="action">
    
       </td>
     </tr>
     {% endfor %}
    </table>
  </div>    
  {% else %}
  <p class="error_msg"> il n'exit aucune demande d'emprunte </p>

  {% endif %}

</div>
</div>

{% endblock %}

appBibliotheque/templates/appBibliotheque/dashboard/users.html
{% extends './base.html' %}
{% load static %}
{% block header %}
Liste Users
{% endblock %}
{% block content %}
{% if users %}
<div class="btndash">
 <a href="{% url 'page_ajout' %}">ajouter user   <i class="fa-solid fa-plus"></i></a>

</div>


 <div class="content">  
 <div style="overflow-x:auto;">
 
    

   <table>
     <tr>
       <th>Usernames</th>
       <th>Email</th>
       <th>Est_bibliothecaire</th>
       <th>Nb Emprunts</th>
       <th>Action</th>
       
     </tr>
     {% for u in users %}
     <tr>
       
       <td>{{u.username}}</td>
       <td>{{u.email}}</td>
       {% if u.est_bibliothecaire %}
         <td class="etat"> <span class="true">true</span>
       {% else %}
         <td class="etat"> <span class="false">false</span>
       {% endif %}
       <td>{{ u.emprunter_set.count }}</td>
       <td class="action">
       <!--  <a href=""><i class="fa-solid fa-pen-to-square"></i> -->
         <!-- <a href="{% url  'delete_user' u.username %}"><i class="fa-solid fa-trash"></i></a> -->
         <a href="#" onclick="confirmDelete('{{u.username}}')"><i class="fa-solid fa-trash"></i></a>
       <!--  <a><i class="fa-solid fa-eye"></i></a> -->
       </td>
     </tr>
     {% endfor %}
   </table>
   {% else %}
   
    <p class="error_msg"> {{message}} </p>
      
  
  </div>    
  
</div>
</div>
{% endif %}
<script>
  function confirmDelete(username) {
      Swal.fire({
          title: 'Are you sure?',
          text: 'You won\'t be able to revert this!',
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
          if (result.isConfirmed) {
              // If the user confirms the deletion, navigate to the delete URL
              window.location.href = window.location.origin + "/delete_user/" + username;
          }
      });
  }
  </script>
  
{% endblock %}